class JobLib:
    m_job = {
        'Bow Master': {
            'class': 'Bowman',
            'Weapon': ['Bow'],
            'Secondary': ['Arrow Fletching'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1309, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 120, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': -0.1,
            '# mdef': 0, '% mdef': -0.1,
            '# accuracy': 345, '% accuracy': 0.35,
            '# avoid': 225, '% avoid': 0.3,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 160, '# jump': 0,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2875,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.55,
            '% Final Damage': 0,
            '% Crit Rate': 0.7,
            '% Min Crit': 0.35,
            '% Max Crit': 0.8,
            '% Status Resistance': 0.2,
            '% Skill Damage': 1.95,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.1,
            '% Hyper Guard Break': 0,
            '# Skill Delay': [1],
            },
        'dummy': {
            'class': 'Bowman',
            'Weapon': ['Bow'],
            'Secondary': ['Arrow Fletching'],
            'Emblem': ['Explorer'],
            '# str': 4, '% str': 0,
            '# dex': 1239, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.05,
            '% Min Crit': 0.2,
            '% Max Crit': 0.5,
            '% Status Resistance': 0,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0,
            '# Skill Delay': [1],
            },
        }
    m_weaponMultiplier = {
        'None': 0,
        'One-handed Sword': 1.2,
        'Two-handed Sword': 1.34,
        'One-handed Axe': 1.2,
        'Two-handed Axe': 1.34,
        'One-handed Mace': 1.2,
        'Two-handed Mace': 1.34,
        'Spear': 1.49,
        'Polearm': 1.49,
        'Wand': [1.2, 1],
        'Staff': [1.2, 1],
        'Bow': 1.3,
        'Crossbow': 1.35,
        'Claw': 1.75,
        'Dagger': 1.3,
        'Gun': 1.5,
        'Knuckle': 1.7,
        'Katara': 1.3,
        'Cane': 1.3,
        'Whip Blade': 1.5,
        'Desperado': 1.3,
        'Shining Rod': 1.2,
        'Cannon': 1.8,
        'Soul Shooter': 1.7,
        'Katana': 1.25,
        'Fan': 1.35,
        'Long Sword': 1.34,
        'Great Sword': 1.49,
        'Dual Bowguns': 1.32,
        }

if __name__ == '__main__':
    print JobLib.m_job['Bow Master'].keys()
        
            
