class BossLib:
    m_counter = {
        #attempt, attempt, defeat, defeat
        'Zakum': ('day', 2, 'day', 2),
        'Horntail': ('day', 2, 'day', 2),
        'Pink Bean': ('day', 1, 'day', 1),
        'Von Leon': ('day', 1, 'day', 1),
        'Cygnus': ('day', 1, 'week', 1),
        'Arkarium': ('day', 1, 'day', 1),
        'Hilla': ('day', 2, 'day', 2),
        'eMagnus': ('day', -1, 'day', 1),
        'nMagnus': ('day', -1, 'day', 1),
        'hMagnus': ('day', -1, 'week', 1),
        'nPierre': ('day', -1, 'day', 1),
        'nVB': ('day', -1, 'day', 1),
        'nQueen': ('day', -1, 'day', 1),
        'nVellum': ('day', -1, 'day', 1),
        'cPierre': ('day', -1, 'week', 1),
        'cVB': ('day', -1, 'week', 1),
        'cQueen': ('day', -1, 'week', 1),
        'cVellum': ('day', -1, 'week', 1),
        'Gollux': ('day', 3, 'day', 1),
        
        }
    m_lib = {
        'Easy Zakum': {
            'counter': 'Zakum',
            'dps': 4000,
            'defense': 0.2,
            'resistance': 0,
            'reward': {
                'Boss Coin': (5, 0.1),
                'Meso': (1000000, 0.1),
                },
            'description': "Zakum was a spirit sealed in a tree deep in the mines of El Nath. A mining town that once existed nearby eventually discovered this tree. At the time, Zakum was a peaceful monster that had no enemies, but the greed of the miners corrupted it. As the spirit was corrupted, it grew smarter, and finally became capable of controlling the town's populace. It forced them to build an enormous statue in tribute to it. The now evil spirit of Zakum possessed the statue, subjugated all the humans and eventually killed everyone in the town. Zakum now rests deep in the lava caves, waiting for powerful players to challenge his might.",
            'AP cost': 10,
            },
        'Normal Zakum': {
            'counter': 'Zakum',
            'dps': 5000,
            'defense': 0.4,
            'resistance': 0,
            'reward': {
                'Boss Coin': (10, 0.1),
                'Meso': (5000000, 0.1),
                },
            'description': "Zakum was a spirit sealed in a tree deep in the mines of El Nath. A mining town that once existed nearby eventually discovered this tree. At the time, Zakum was a peaceful monster that had no enemies, but the greed of the miners corrupted it. As the spirit was corrupted, it grew smarter, and finally became capable of controlling the town's populace. It forced them to build an enormous statue in tribute to it. The now evil spirit of Zakum possessed the statue, subjugated all the humans and eventually killed everyone in the town. Zakum now rests deep in the lava caves, waiting for powerful players to challenge his might.",
            'AP cost': 10,
            },
        'Chaos Zakum': {
            'counter': 'Zakum',
            'dps': 80000,
            'defense': 0.5,
            'resistance': 0,
            'reward': {
                'Boss Coin': (20, 0.1),
                'Meso': (10000000, 0.1),
                },
            'description': "Zakum was a spirit sealed in a tree deep in the mines of El Nath. A mining town that once existed nearby eventually discovered this tree. At the time, Zakum was a peaceful monster that had no enemies, but the greed of the miners corrupted it. As the spirit was corrupted, it grew smarter, and finally became capable of controlling the town's populace. It forced them to build an enormous statue in tribute to it. The now evil spirit of Zakum possessed the statue, subjugated all the humans and eventually killed everyone in the town. Zakum now rests deep in the lava caves, waiting for powerful players to challenge his might.",
            'AP cost': 10,
            },
        'Easy Horntail': {
            'counter': 'Horntail',
            'dps': 11000,
            'defense': 0.4,
            'resistance': 0,
            'reward': {
                'Boss Coin': (10, 0.1),
                'Meso': (5000000, 0.1),
                },
            'description': "Horntail is an evil power-hungry dragon who rebelled against the Nine Spirits' rule and distorted the area with evil in order to kidnap an egg of Nine Spirit Dragon and consolidate its power over Minar Forest. Horntail now holds an ambitious wish of ruling over the entire Minar Forest. It now waits for powerful Maplers to enter the Cave of Life to challenge it.",
            'AP cost': 10,
            },
        'Normal Horntail': {
            'counter': 'Horntail',
            'dps': 18000,
            'defense': 0.4,
            'resistance': 0,
            'reward': {
                'Boss Coin': (15, 0.1),
                'Meso': (10000000, 0.1),
                },
            'description': "Horntail is an evil power-hungry dragon who rebelled against the Nine Spirits' rule and distorted the area with evil in order to kidnap an egg of Nine Spirit Dragon and consolidate its power over Minar Forest. Horntail now holds an ambitious wish of ruling over the entire Minar Forest. It now waits for powerful Maplers to enter the Cave of Life to challenge it.",
            'AP cost': 10,
            },
        'Chaos Horntail': {
            'counter': 'Horntail',
            'dps': 360000,
            'defense': 0.5,
            'resistance': 0,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Horntail is an evil power-hungry dragon who rebelled against the Nine Spirits' rule and distorted the area with evil in order to kidnap an egg of Nine Spirit Dragon and consolidate its power over Minar Forest. Horntail now holds an ambitious wish of ruling over the entire Minar Forest. It now waits for powerful Maplers to enter the Cave of Life to challenge it.",
            'AP cost': 10,
            },
        'Normal Pink Bean': {
            'counter': 'Pink Bean',
            'dps': 220000,
            'defense': 0.7,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Pink Bean is a unspecified Transcendent from Bean World. He is a overall pink creature, with a white belly, and purple horns and a purple tail. Being a Transcendent he has many powers. In the Maple World, while Kirston was trying to summon the Black Mage, something went wrong and he instead summoned Pink Bean.",
            'AP cost': 10,
            },
        'Chaos Pink Bean': {
            'counter': 'Pink Bean',
            'dps': 2000000,
            'defense': 1.8,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (100, 0.1),
                'Meso': (50000000, 0.1),
                },
            'description': "Pink Bean is a unspecified Transcendent from Bean World. He is a overall pink creature, with a white belly, and purple horns and a purple tail. Being a Transcendent he has many powers. In the Maple World, while Kirston was trying to summon the Black Mage, something went wrong and he instead summoned Pink Bean.",
            'AP cost': 10,
            },
        'Easy Von Leon': {
            'counter': 'Von Leon',
            'dps': 23000,
            'defense': 0.5,
            'resistance': 0,
            'reward': {
                'Boss Coin': (20, 0.1),
                'Meso': (10000000, 0.1),
                },
            'description': "Von Leon, also known as the Lion King, is one of the commanders of the Black Mage.",
            'AP cost': 10,
            },
        'Normal Von Leon': {
            'counter': 'Von Leon',
            'dps': 49000,
            'defense': 0.8,
            'resistance': 0,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Von Leon, also known as the Lion King, is one of the commanders of the Black Mage.",
            'AP cost': 10,
            },
        'Empress Cygnus': {
            'counter': 'Cygnus',
            'dps': 960000,
            'defense': 1,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (200, 0.1),
                'Cygnus Coin': (100, 0.1),
                'Meso': (50000000, 0.1),
                },
            'description': "In the near future, Empress Cygnus became interested in the World Tree, the Transcendence of Life. The World Tree is said to grant immense powers, and Cygnus wishes to use this power against the Black Mage. Neinheart, however, advised against doing so. Eventually, Cygnus and her knights went to search for the World Tree. They succeeded, but fell into a trap laid by the Black Mage. Cygnus and her knights became corrupted and the island of =Ereve is no longer held up by the magic created by Cygnus, and descended to Victoria Island.",
            'AP cost': 10,
            },
        'Easy Arkarium': {
            'counter': 'Arkarium',
            'dps': 280000,
            'defense': 0.6,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (20, 0.1),
                'Meso': (10000000, 0.1),
                },
            'description': "Arkarium is one of the commanders of the Black Mage and is said to be his right-hand man.",
            'AP cost': 10,
            },
        'Normal Arkarium': {
            'counter': 'Arkarium',
            'dps': 590000,
            'defense': 0.6,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (50, 0.1),
                'Meso': (20000000, 0.1),
                },
            'description': "Arkarium is one of the commanders of the Black Mage and is said to be his right-hand man.",
            'AP cost': 10,
            },
        'Normal Hilla': {
            'counter': 'Hilla',
            'dps': 14000,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (15, 0.1),
                'Meso': (10000000, 0.1),
                },
            'description': "Hilla is one of the commanders of the Black Mage. Formerly one of the chief shamanesses of Azwan, she was overcome with greed and handed over the city to the Black Mage in exchange for eternal power, youth, and beauty. With the power of necromancy in her hand, Hilla revived the deceased population of Azwan for her personal undead army, and lined her kingdom with magical totems to continuously reanimate her fallen soldiers.",
            'AP cost': 10,
            },
        'Hard Hilla': {
            'counter': 'Hilla',
            'dps': 750000,
            'defense': 3.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (100, 0.1),
                'Meso': (50000000, 0.1),
                },
            'description': "Hilla is one of the commanders of the Black Mage. Formerly one of the chief shamanesses of Azwan, she was overcome with greed and handed over the city to the Black Mage in exchange for eternal power, youth, and beauty. With the power of necromancy in her hand, Hilla revived the deceased population of Azwan for her personal undead army, and lined her kingdom with magical totems to continuously reanimate her fallen soldiers.",
            'AP cost': 10,
            },
        'Easy Magnus': {
            'counter': 'eMagnus',
            'dps': 8500,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Magnus is a former commander of the Black Mage and a commander of Gerald Darmoor. He is of the Nova race, much like Kaiser and Angelic Buster.",
            'AP cost': 10,
            },
        'Normal Magnus': {
            'counter': 'nMagnus',
            'dps': 170000,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (50, 0.1),
                'Meso': (30000000, 0.1),
                },
            'description': "Magnus is a former commander of the Black Mage and a commander of Gerald Darmoor. He is of the Nova race, much like Kaiser and Angelic Buster.",
            'AP cost': 10,
            },
        'Hard Magnus': {
            'counter': 'hMagnus',
            'dps': 1230000,
            'defense': 1.2,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (200, 0.1),
                'Magnus Coin': (6, 1),
                'Magnus Coin B': (5, 0.3),
                'Meso': (50000000, 0.1),
                },
            'description': "Magnus is a former commander of the Black Mage and a commander of Gerald Darmoor. He is of the Nova race, much like Kaiser and Angelic Buster.",
            'AP cost': 10,
            },
        'Normal Pierre': {
            'counter': 'nPierre',
            'dps': 38000,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Pierre is one of the four main bosses of Root Abyss and Damien's generals.",
            'AP cost': 10,
            },
        'Chaos Pierre': {
            'counter': 'cPierre',
            'dps': 2610000,
            'defense': 0.8,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (100, 0.1),
                'Pierre Coin': (25, 0.2),
                'Meso': (15000000, 0.1),
                },
            'description': "Pierre is one of the four main bosses of Root Abyss and Damien's generals.",
            'AP cost': 10,
            },
        'Normal Von Bon': {
            'counter': 'nVB',
            'dps': 49000,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Von Bon is one of the four main bosses of Root Abyss and Damien's generals.",
            'AP cost': 10,
            },
        'Chaos Von Bon': {
            'counter': 'cVB',
            'dps': 1590000,
            'defense': 1,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (100, 0.1),
                'VonBon Coin': (25, 0.2),
                'Meso': (15000000, 0.1),
                },
            'description': "Von Bon is one of the four main bosses of Root Abyss and Damien's generals.",
            'AP cost': 10,
            },
        'Normal Crimson Queen': {
            'counter': 'nQueen',
            'dps': 30000,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Crimson Queen is one of the four main bosses of Root Abyss and Damien's generals.",
            'AP cost': 10,
            },
        'Chaos Crimson Queen': {
            'counter': 'cQueen',
            'dps': 3345000,
            'defense': 1.2,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (100, 0.1),
                'Queen Coin': (25, 0.2),
                'Meso': (15000000, 0.1),
                },
            'description': "Crimson Queen is one of the four main bosses of Root Abyss and Damien's generals.",
            'AP cost': 10,
            },
        'Normal Vellum': {
            'counter': 'nVellum',
            'dps': 63000,
            'defense': 0.55,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (30, 0.1),
                'Meso': (15000000, 0.1),
                },
            'description': "Vellum is the final boss of Root Abyss, and is also one of Damien's summoned generals.",
            'AP cost': 10,
            },
        'Chaos Vellum': {
            'counter': 'cVellum',
            'dps': 5500000,
            'defense': 3,
            'resistance': 0.5,
            'reward': {
                'Boss Coin': (100, 0.1),
                'Vellum Coin': (25, 0.2),
                'Meso': (15000000, 0.1),
                },
            'description': "Vellum is the final boss of Root Abyss, and is also one of Damien's summoned generals.",
            'AP cost': 10,
            },
        'Easy Gollux': {
            'counter': 'Gollux',
            'dps': 6500,
            'defense': 0.1,
            'resistance': 0.5,
            'reward': {
                'Gollux Coin': (10, 0.9),
                'Gollux Coin B': (1, 0.2),
                'Meso': (10000000, 0.1),
                },
            'description': "Gollux is a giant treelike monster, and the final boss of Tynerum's storyline.",
            'AP cost': 10,
            },
        'Normal Gollux': {
            'counter': 'Gollux',
            'dps': 100000,
            'defense': 0.15,
            'resistance': 0.5,
            'reward': {
                'Gollux Coin': (20, 0.9),
                'Gollux Coin B': (1, 0.2),
                'Gollux Coin A': (1, 0.2),
                'Meso': (20000000, 0.1),
                },
            'description': "Gollux is a giant treelike monster, and the final boss of Tynerum's storyline.",
            'AP cost': 10,
            },
        'Hard Gollux': {
            'counter': 'Gollux',
            'dps': 460000,
            'defense': 0.5,
            'resistance': 0.5,
            'reward': {
                'Gollux Coin': (30, 0.9),
                'Gollux Coin B': (1, 0.2),
                'Gollux Coin A': (1, 0.2),
                'Gollux Coin S': (1, 0.1),
                'Meso': (30000000, 0.1),
                },
            'description': "Gollux is a giant treelike monster, and the final boss of Tynerum's storyline.",
            'AP cost': 10,
            },
        'Hell Gollux': {
            'counter': 'Gollux',
            'dps': 4300000,
            'defense': 0.8,
            'resistance': 0.5,
            'reward': {
                'Gollux Coin': (40, 0.9),
                'Gollux Coin B': (1, 0.2),
                'Gollux Coin A': (1, 0.2),
                'Gollux Coin S': (1, 0.1),
                'Gollux Coin SS': (1, 0.1),
                'Meso': (50000000, 0.1),
                },
            'description': "Gollux is a giant treelike monster, and the final boss of Tynerum's storyline.",
            'AP cost': 10,
            },
        }

    m_bosses = [
        'Easy Zakum',
        'Normal Zakum',
        'Chaos Zakum',
        'Easy Horntail',
        'Normal Horntail',
        'Chaos Horntail',
        'Easy Von Leon',
        'Normal Von Leon',
        'Normal Hilla',
        'Hard Hilla',
        'Easy Arkarium',
        'Normal Arkarium',
        'Normal Pink Bean',
        'Chaos Pink Bean',
        'Easy Magnus',
        'Normal Magnus',
        'Normal Crimson Queen',
        'Normal Pierre',
        'Normal Von Bon',
        'Normal Vellum',
        'Easy Gollux',
        'Normal Gollux',
        'Hard Gollux',
        'Hell Gollux',
        'Hard Magnus',
        'Empress Cygnus',
        'Chaos Crimson Queen',
        'Chaos Pierre',
        'Chaos Von Bon',
        'Chaos Vellum',
        ]
        
            
