class EquipLib:
    'Equipment library'

    m_libHat = {
        'Royal Dunwitch Hat': {
            'name': 'Royal Dunwitch Hat',
            'type': 'Hat',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 40,
            'luk': 40,
            'hp': 360,
            'mp': 360,
            'watt': 0,
            'matt': 2,
            'wdef': 180,
            'mdef': 240,
            'accuracy': 240,
            'avoid': 120,
            'boss': 0,
            'pdr': 0.1,
            'slot': 11,
            'setId': 1,
            # market info
            'cost': ['Meso','Queen Coin'],
            'value': [50000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Royal Assassin Hood': {
            'name': 'Royal Assassin Hood',
            'type': 'Hat',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 40,
            'int': 0,
            'luk': 40,
            'hp': 360,
            'mp': 360,
            'watt': 2,
            'matt': 0,
            'wdef': 300,
            'mdef': 0,
            'accuracy': 240,
            'avoid': 120,
            'boss': 0,
            'pdr': 0.1,
            'slot': 11,
            'setId': 2,
            # market info
            'cost': ['Meso','Queen Coin'],
            'value': [74000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Royal Warrior Helm': {
            'name': 'Royal Warrior Helm',
            'type': 'Hat',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 360,
            'mp': 360,
            'watt': 2,
            'matt': 0,
            'wdef': 390,
            'mdef': 0,
            'accuracy': 240,
            'avoid': 120,
            'boss': 0,
            'pdr': 0.1,
            'slot': 11,
            'setId': 2,
            # market info
            'cost': ['Meso','Queen Coin'],
            'value': [57000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Royal Ranger Beret': {
            'name': 'Royal Ranger Beret',
            'type': 'Hat',
            'class': 'Bowman',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 360,
            'mp': 360,
            'watt': 2,
            'matt': 0,
            'wdef': 300,
            'mdef': 0,
            'accuracy': 240,
            'avoid': 120,
            'boss': 0,
            'pdr': 0.1,
            'slot': 11,
            'setId': 2,
            # market info
            'cost': ['Meso','Queen Coin'],
            'value': [30000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Royal Wanderer Hat': {
            'name': 'Royal Wanderer Hat',
            'type': 'Hat',
            'class': 'Pirate',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 360,
            'mp': 360,
            'watt': 2,
            'matt': 0,
            'wdef': 300,
            'mdef': 0,
            'accuracy': 240,
            'avoid': 120,
            'boss': 0,
            'pdr': 0.1,
            'slot': 11,
            'setId': 2,
            # market info
            'cost': ['Meso','Queen Coin'],
            'value': [24000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        }
    
    m_libTop = {
        'Eagle Eye Dunwitch Robe': {
            'name': 'Eagle Eye Dunwitch Robe',
            'type': 'Top',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 30,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 0,
            'matt': 2,
            'wdef': 120,
            'mdef': 150,
            'accuracy': 30,
            'avoid': 30,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','VonBon Coin'],
            'value': [25000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Eagle Eye Assassin Shirt': {
            'name': 'Eagle Eye Assassin Shirt',
            'type': 'Top',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 30,
            'int': 0,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 135,
            'mdef': 135,
            'accuracy': 12,
            'avoid': 48,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','VonBon Coin'],
            'value': [31000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Eagle Eye Warrior Armor': {
            'name': 'Eagle Eye Warrior Armor',
            'type': 'Top',
            'class': 'Warrior',
            'level': 150,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 210,
            'mdef': 60,
            'accuracy': 30,
            'avoid': 30,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','VonBon Coin'],
            'value': [26000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Eagle Eye Ranger Cowl': {
            'name': 'Eagle Eye Ranger Cowl',
            'type': 'Top',
            'class': 'Bowman',
            'level': 150,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 135,
            'mdef': 135,
            'accuracy': 48,
            'avoid': 12,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','VonBon Coin'],
            'value': [16000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Eagle Eye Wanderer Coat': {
            'name': 'Eagle Eye Wanderer Coat',
            'type': 'Top',
            'class': 'Pirate',
            'level': 150,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 135,
            'mdef': 135,
            'accuracy': 30,
            'avoid': 30,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','VonBon Coin'],
            'value': [29000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        }
    m_libOverall = {
        'Dragon Tail Mage Robe' : {
            'name': 'Dragon Tail Mage Robe',
            'type': 'Overall',
            'class': 'Magician',
            'level': 140,
            'str': 0,
            'dex': 0,
            'int': 30,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 0,
            'matt': 2,
            'wdef': 200,
            'mdef': 250,
            'accuracy': 50,
            'avoid': 50,
            'boss': 0,
            'pdr': 0,
            'slot': 12,
            'setId': 1,
            # market info
            'cost': ['Meso','Cygnus Coin'],
            'value': [13500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Lionheart Battle Mail' : {
            'name': 'Lionheart Battle Mail',
            'type': 'Overall',
            'class': 'Warrior',
            'level': 140,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 350,
            'mdef': 100,
            'accuracy': 50,
            'avoid': 50,
            'boss': 0,
            'pdr': 0,
            'slot': 12,
            'setId': 1,
            # market info
            'cost': ['Meso','Cygnus Coin'],
            'value': [12500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Falcon Wing Sentinel Suit' : {
            'name': 'Falcon Wing Sentinel Suit',
            'type': 'Overall',
            'class': 'Bowman',
            'level': 140,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 225,
            'mdef': 225,
            'accuracy': 80,
            'avoid': 20,
            'boss': 0,
            'pdr': 0,
            'slot': 12,
            'setId': 1,
            # market info
            'cost': ['Meso','Cygnus Coin'],
            'value': [6500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Raven Horn Chaser Armor' : {
            'name': 'Raven Horn Chaser Armor',
            'type': 'Overall',
            'class': 'Thief',
            'level': 140,
            'str': 0,
            'dex': 30,
            'int': 0,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 225,
            'mdef': 225,
            'accuracy': 20,
            'avoid': 80,
            'boss': 0,
            'pdr': 0,
            'slot': 12,
            'setId': 1,
            # market info
            'cost': ['Meso','Cygnus Coin'],
            'value': [13500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Sharktooth Skipper Coat' : {
            'name': 'Sharktooth Skipper Coat',
            'type': 'Overall',
            'class': 'Pirate',
            'level': 140,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 225,
            'mdef': 225,
            'accuracy': 50,
            'avoid': 50,
            'boss': 0,
            'pdr': 0,
            'slot': 12,
            'setId': 1,
            # market info
            'cost': ['Meso','Cygnus Coin'],
            'value': [8000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libBottom = {
        'Trixter Dunwitch Pants' : {
            'name': 'Trixter Dunwitch Pants',
            'type': 'Bottom',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 30,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 0,
            'matt': 2,
            'wdef': 120,
            'mdef': 150,
            'accuracy': 30,
            'avoid': 30,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','Pierre Coin'],
            'value': [74000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Trixter Warrior Pants' : {
            'name': 'Trixter Warrior Pants',
            'type': 'Bottom',
            'class': 'Warrior',
            'level': 150,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 210,
            'mdef': 60,
            'accuracy': 30,
            'avoid': 30,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','Pierre Coin'],
            'value': [74000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Trixter Assassin Pants' : {
            'name': 'Trixter Assassin Pants',
            'type': 'Bottom',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 30,
            'int': 0,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 135,
            'mdef': 135,
            'accuracy': 12,
            'avoid': 48,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','Pierre Coin'],
            'value': [112500000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Trixter Ranger Pants' : {
            'name': 'Trixter Ranger Pants',
            'type': 'Bottom',
            'class': 'Bowman',
            'level': 150,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 135,
            'mdef': 135,
            'accuracy': 48,
            'avoid': 12,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','Pierre Coin'],
            'value': [34500000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        'Trixter Wanderer Pants' : {
            'name': 'Trixter Wanderer Pants',
            'type': 'Bottom',
            'class': 'Pirate',
            'level': 150,
            'str': 30,
            'dex': 30,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 0,
            'wdef': 135,
            'mdef': 135,
            'accuracy': 30,
            'avoid': 30,
            'boss': 0,
            'pdr': 0.05,
            'slot': 7,
            'setId': 1,
            # market info
            'cost': ['Meso','Pierre Coin'],
            'value': [31000000, 5],
            'stock': [10, -1],
            'max': [20, -1],
            'supply': [10, -1],
            },
        }
    m_libShoe = {
        'Tyrant Hermes Boots' : {
            'name': 'Tyrant Hermes Boots',
            'type': 'Shoe',
            'class': 'Magician',
            'level': 150,
            'str': 50,
            'dex': 50,
            'int': 50,
            'luk': 50,
            'hp': 0,
            'mp': 0,
            'watt': 30,
            'matt': 30,
            'wdef': 130,
            'mdef': 130,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 2,
            'setId': 0,
            # market info
            'cost': ['Meso','Magnus Coin'],
            'value': [1, 70],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libCape = {
        'Tyrant Hermes Cloak' : {
            'name': 'Tyrant Hermes Cloak',
            'type': 'Cape',
            'class': 'Magician',
            'level': 150,
            'str': 50,
            'dex': 50,
            'int': 50,
            'luk': 50,
            'hp': 0,
            'mp': 0,
            'watt': 30,
            'matt': 30,
            'wdef': 150,
            'mdef': 150,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 2,
            'setId': 0,
            # market info
            'cost': ['Meso','Magnus Coin B'],
            'value': [1, 1],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libBelt = {
        'Tyrant Hermes Belt' : {
            'name': 'Tyrant Hermes Belt',
            'type': 'Belt',
            'class': 'Magician',
            'level': 150,
            'str': 50,
            'dex': 50,
            'int': 50,
            'luk': 50,
            'hp': 0,
            'mp': 0,
            'watt': 25,
            'matt': 25,
            'wdef': 105,
            'mdef': 105,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 1,
            'setId': 0,
            # market info
            'cost': ['Meso','Magnus Coin'],
            'value': [1, 100],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libGlove = {
        'Tyrant Hermes Gloves' : {
            'name': 'Tyrant Hermes Gloves',
            'type': 'Glove',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 12,
            'luk': 12,
            'hp': 0,
            'mp': 300,
            'watt': 0,
            'matt': 15,
            'wdef': 0,
            'mdef': 160,
            'accuracy': 35,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 1,
            'setId': 0,
            # market info
            'cost': ['Meso','Shadow Coin'],
            'value': [1, 400],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libEye = {
        'Sweetwater Glasses' : {
            'name': 'Sweetwater Glasses',
            'type': 'Eye',
            'class': 'All',
            'level': 160,
            'str': 10,
            'dex': 10,
            'int': 10,
            'luk': 10,
            'hp': 240,
            'mp': 240,
            'watt': 0,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 5,
            'setId': 0,
            # market info
            'cost': ['Meso','Denaro'],
            'value': [1, 250],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libFace = {
        'Sweetwater Tattoo' : {
            'name': 'Sweetwater Tattoo',
            'type': 'Face',
            'class': 'All',
            'level': 160,
            'str': 5,
            'dex': 5,
            'int': 5,
            'luk': 5,
            'hp': 120,
            'mp': 120,
            'watt': 0,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 5,
            'setId': 0,
            # market info
            'cost': ['Meso','Denaro'],
            'value': [1, 250],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libRing = {
        'Superior Gollux Ring' : {
            'name': 'Superior Gollux Ring',
            'type': 'Ring',
            'class': 'All',
            'level': 150,
            'str': 10,
            'dex': 10,
            'int': 10,
            'luk': 10,
            'hp': 250,
            'mp': 250,
            'watt': 8,
            'matt': 8,
            'wdef': 150,
            'mdef': 150,
            'accuracy': 100,
            'avoid': 100,
            #TODO: speed
            'boss': 0,
            'pdr': 0,
            'slot': 6,
            'setId': 5,
            # market info
            'cost': ['Meso','Gollux Coin'],
            'value': [1, 160],
            'stock': [5, 1],
            'max': [10, 1],
            'supply': [5, 0],
            },
        }
    m_libPendant = {
        'Superior Engraved Gollux Pendant' : {
            'name': 'Superior Engraved Gollux Pendant',
            'type': 'Pendant',
            'class': 'All',
            'level': 150,
            'str': 28,
            'dex': 28,
            'int': 28,
            'luk': 28,
            'hp': 300,
            'mp': 300,
            'watt': 5,
            'matt': 5,
            'wdef': 100,
            'mdef': 100,
            'accuracy': 50,
            'avoid': 50,
            'boss': 0,
            'pdr': 0,
            'slot': 6,
            'setId': 5,
            # market info
            'cost': ['Meso','Gollux Coin SS'],
            'value': [1, 1],
            'stock': [5, 1],
            'max': [10, 1],
            'supply': [5, 1],
            },
        }
    m_libEarring = {
        'Superior Gollux Earrings' : {
            'name': 'Superior Gollux Earrings',
            'type': 'Earring',
            'class': 'All',
            'level': 150,
            'str': 15,
            'dex': 15,
            'int': 15,
            'luk': 15,
            'hp': 150,
            'mp': 150,
            'watt': 10,
            'matt': 10,
            'wdef': 100,
            'mdef': 100,
            'accuracy': 100,
            'avoid': 100,
            'boss': 0,
            'pdr': 0,
            'slot': 7,
            'setId': 5,
            # market info
            'cost': ['Meso','Gollux Coin'],
            'value': [1, 170],
            'stock': [5, 1],
            'max': [10, 1],
            'supply': [5, 0],
            },
        }
    m_libBadge = {
        'Ghost Ship Exorcist' : {
            'name': 'Ghost Ship Exorcist',
            'type': 'Badge',
            'class': 'All',
            'level': 150,
            'str': 3,
            'dex': 3,
            'int': 3,
            'luk': 3,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 2,
            'wdef': 70,
            'mdef': 70,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 1,
            'setId': 0,
            # market info
            'cost': ['Meso'],
            'value': [0],
            'stock': [1],
            'max': [1],
            'supply': [0],
            },
        }
    m_libWeapon = {
        'Fafnir Mana Crown' : {
            'name': 'Fafnir Mana Crown',
            'type': 'Weapon',
            'category': 'Staff',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 40,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 126,
            'matt': 204,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 1,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [99500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Wind Chaser' : {
            'name': 'Fafnir Wind Chaser',
            'type': 'Weapon',
            'category': 'Bow',
            'class': 'Bowman',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 160,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [74500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Windwing Shooter' : {
            'name': 'Fafnir Windwing Shooter',
            'type': 'Weapon',
            'category': 'Crossbow',
            'class': 'Bowman',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 164,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [92000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Angelic Shooter' : {
            'name': 'Fafnir Angelic Shooter',
            'type': 'Weapon',
            'category': 'Soul Shooter',
            'class': 'Pirate',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 128,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [10000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Battle Cleaver' : {
            'name': 'Fafnir Battle Cleaver',
            'type': 'Weapon',
            'category': 'Two-handed Axe',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 171,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [9500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Brionak' : {
            'name': 'Fafnir Brionak',
            'type': 'Weapon',
            'category': 'Spear',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 171,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [18500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Claire Ciel' : {
            'name': 'Fafnir Claire Ciel',
            'type': 'Weapon',
            'category': 'Cane',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 40,
            'int': 0,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 164,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [42500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Damascus' : {
            'name': 'Fafnir Damascus',
            'type': 'Weapon',
            'category': 'Dagger',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 40,
            'int': 0,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 160,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [112000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Death Bringer' : {
            'name': 'Fafnir Death Bringer',
            'type': 'Weapon',
            'category': 'Desperado',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 0,
            'int': 0,
            'luk': 0,
            'hp': 2000,
            'mp': 0,
            'watt': 171,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [65000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Dual Windwing' : {
            'name': 'Fafnir Dual Windwing',
            'type': 'Weapon',
            'category': 'Dual Bowgun',
            'class': 'Bowman',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 160,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [32000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Guardian Hammer' : {
            'name': 'Fafnir Guardian Hammer',
            'type': 'Weapon',
            'category': 'One-handed Mace',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 164,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [14500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Indigo Flash' : {
            'name': 'Fafnir Indigo Flash',
            'type': 'Weapon',
            'category': 'Fan',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 40,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 126,
            'matt': 204,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [36000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Lightning Striker' : {
            'name': 'Fafnir Lightning Striker',
            'type': 'Weapon',
            'category': 'Two-handed Mace',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 171,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [9000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Lost Cannon' : {
            'name': 'Fafnir Lost Cannon',
            'type': 'Weapon',
            'category': 'Cannon',
            'class': 'Pirate',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 175,
            'matt': 0,
            'wdef': 121,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [20000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Mana Cradle' : {
            'name': 'Fafnir Mana Cradle',
            'type': 'Weapon',
            'category': 'Shining Rod',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 40,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 119,
            'matt': 201,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [52000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Mana Taker' : {
            'name': 'Fafnir Mana Taker',
            'type': 'Weapon',
            'category': 'Wand',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 40,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 119,
            'matt': 201,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [71500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Mistilteinn' : {
            'name': 'Fafnir Mistilteinn',
            'type': 'Weapon',
            'category': 'One-handed Sword',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 164,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [13000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Moon Glaive' : {
            'name': 'Fafnir Moon Glaive',
            'type': 'Weapon',
            'category': 'Pole Arm',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 153,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [28500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Penitent Tears' : {
            'name': 'Fafnir Penitent Tears',
            'type': 'Weapon',
            'category': 'Two-handed Sword',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 171,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [91000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Perry Talon' : {
            'name': 'Fafnir Perry Talon',
            'type': 'Weapon',
            'category': 'Knuckle',
            'class': 'Pirate',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 128,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [77000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Raven Ring' : {
            'name': 'Fafnir Raven Ring',
            'type': 'Weapon',
            'category': 'Katana',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 164,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [39000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Risk Holder' : {
            'name': 'Fafnir Risk Holder',
            'type': 'Weapon',
            'category': 'Claw',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 40,
            'int': 0,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 86,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [453500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Scepter' : {
            'name': 'Fafnir Scepter',
            'type': 'Weapon',
            'category': 'Scepter',
            'class': 'Magician',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 40,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 119,
            'matt': 201,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [16500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Split Edge (Pirate)' : {
            'name': 'Fafnir Split Edge (Pirate)',
            'type': 'Weapon',
            'category': 'Whip Blade',
            'class': 'Pirate',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 128,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [25500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Split Edge (Thief)' : {
            'name': 'Fafnir Split Edge (Thief)',
            'type': 'Weapon',
            'category': 'Whip Blade',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 40,
            'int': 0,
            'luk': 40,
            'hp': 0,
            'mp': 0,
            'watt': 128,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [19500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Twin Clever' : {
            'name': 'Fafnir Twin Clever',
            'type': 'Weapon',
            'category': 'One-handed Axe',
            'class': 'Warrior',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 164,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [12000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Fafnir Zeliska' : {
            'name': 'Fafnir Zeliska',
            'type': 'Weapon',
            'category': 'Gun',
            'class': 'Pirate',
            'level': 150,
            'str': 40,
            'dex': 40,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 125,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 120,
            'avoid': 0,
            'boss': 0.3,
            'pdr': 0.1,
            'slot': 8,
            'setId': 2,
            # market info
            'cost': ['Meso','Vellum Coin'],
            'value': [29000000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        }
    m_libSecondary = {
        'VIP Magician Shield' : {
            'name': 'VIP Magician Shield',
            'type': 'Secondary',
            'category': 'Shield',
            'class': 'Magician',
            'level': 127,
            'str': 0,
            'dex': 0,
            'int': 10,
            'luk': 4,
            'hp': 0,
            'mp': 0,
            'watt': 0,
            'matt': 0,
            'wdef': 110,
            'mdef': 160,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 7,
            'setId': 0,
            # market info
            'cost': ['Meso'],
            'value': [1],
            'stock': [5],
            'max': [10],
            'supply': [5],
            },
        'Fafnir Rapid Edge' : {
            'name': 'Fafnir Rapid Edge',
            'type': 'Secondary',
            'category': 'Katara',
            'class': 'Thief',
            'level': 150,
            'str': 0,
            'dex': 0,
            'int': 0,
            'luk': 30,
            'hp': 0,
            'mp': 0,
            'watt': 81,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 7,
            'setId': 0,
            # market info
            'cost': ['Meso', 'Vellum Coin'],
            'value': [37500000, 5],
            'stock': [5, -1],
            'max': [10, -1],
            'supply': [5, -1],
            },
        'Blasted Feather': {
            'name': 'Blasted Feather',
            'type': 'Secondary',
            'category': 'Arrow Fletching',
            'class': 'Bowman',
            'level': 100,
            'str': 10,
            'dex': 10,
            'int': 0,
            'luk': 0,
            'hp': 0,
            'mp': 0,
            'watt': 3,
            'matt': 0,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 0,
            'setId': 0,
            # market info
            'cost': ['Meso'],
            'value': [1],
            'stock': [5],
            'max': [10],
            'supply': [5],
            },
        }
    m_libEmblem = {
        'Gold Maple Leaf Emblem' : {
            'name': 'Gold Maple Leaf Emblem',
            'type': 'Emblem',
            'category': 'Explorer',
            'class': 'All',
            'level': 100,
            'str': 10,
            'dex': 10,
            'int': 10,
            'luk': 10,
            'hp': 0,
            'mp': 0,
            'watt': 2,
            'matt': 2,
            'wdef': 0,
            'mdef': 0,
            'accuracy': 0,
            'avoid': 0,
            'boss': 0,
            'pdr': 0,
            'slot': 0,
            'setId': 0,
            # market info
            'cost': ['Meso'],
            'value': [0],
            'stock': [-1],
            'max': [-1],
            'supply': [-1],
            },
        }
    m_lib = {
        'Hat': m_libHat,
        'Top': m_libTop,
        'Overall': m_libOverall,
        'Bottom': m_libBottom,
        'Shoe': m_libShoe,
        'Cape': m_libCape,
        'Belt': m_libBelt,
        'Glove': m_libGlove,
        'Eye': m_libEye,
        'Face': m_libFace,
        'Ring': m_libRing,
        'Pendant': m_libPendant,
        'Earring': m_libEarring,
        'Badge': m_libBadge,
        'Weapon': m_libWeapon,
        'Secondary': m_libSecondary,
        'Emblem': m_libEmblem,
        
    }


    @staticmethod
    def getEquip(equipName):
        for equipType in EquipLib.m_lib.values():
            if equipName in equipType.keys():
                return equipType[equipName]
        return None
                
