class EquipSlotLib:

    m_lib = {
        'Hat': ['Hat'],
        'Top': ['Top', 'Overall'],
        'Bottom': ['Bottom'],
        'Shoe': ['Shoe'],
        'Cape': ['Cape'],
        'Belt': ['Belt'],
        'Glove': ['Glove'],
        'Eye': ['Eye'],
        'Face': ['Face'],
        'Ring 1': ['Ring'],
        'Ring 2': ['Ring'],
        'Ring 3': ['Ring'],
        'Ring 4': ['Ring'],
        'Pendant 1': ['Pendant'],
        'Pendant 2': ['Pendant'],
        'Earring': ['Earring'],
        'Shoulder': ['Shoulder'],
        'Badge': ['Badge'],
        'Weapon': ['Weapon'],
        'Secondary': ['Secondary'],
        'Emblem': ['Emblem'],
        }
