class JobLib:
    m_job = {
        'Bow Master': {
            'class': 'Bowman',
            'Weapon': ['Bow'],
            'Secondary': ['Arrow Fletching'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1309, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 120, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': -0.1,
            '# mdef': 0, '% mdef': -0.1,
            '# accuracy': 345, '% accuracy': 0.35,
            '# avoid': 225, '% avoid': 0.3,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 160, '# jump': 0,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2875,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.55,
            '% Final Damage': 0,
            '% Crit Rate': 0.8,
            '% Min Crit': 0.35,
            '% Max Crit': 0.8,
            '% Status Resistance': 0.2,
            '% Skill Damage': 1.95,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.1,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Explorers specialized in using bows. Bow Masters are well-known for their high hits per second with "Hurricane" and "Arrow Platter".\n\nClass: Bowman\nCategory: Explorer\n\nPrimary Weapon: Bow\nSecondary Weapon: Arrow Fletching\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancement Route:\nI:Archer -> II:Hunter -> III:Ranger -> IV:Bow Master\n',
            },
        'Marksman': {
            'class': 'Bowman',
            'Weapon': ['Crossbow'],
            'Secondary': ['Bow Thimble'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1309, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 60, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0.3,
            '# mdef': 0, '% mdef': 0.3,
            '# accuracy': 345, '% accuracy': 0.25,
            '# avoid': 225, '% avoid': -0.5,
            '# hp': 0, '% hp': 0.4,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 160, '# jump': 0,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2875,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.15,
            '% Final Damage': 0,
            '% Crit Rate': 0.8,
            '% Min Crit': 0.2,
            '% Max Crit': 1.2,
            '% Status Resistance': 0.2,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0.8,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.6,
            '% Hyper Critical': 1,
            '# Skill Delay': [1],
            'description':'Explorers specialized in using crossbows. Marksmans are well-known for their single-line high damage skill "Snipe", which has a damage cap of 400,000,000.\n\nClass: Bowman\nCategory: Explorer\n\nPrimary Weapon: Crossbow\nSecondary Weapon: Bow Thimble\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancedment Route:\nI:Archer -> II.Crossbowman -> III.Sniper -> IV.Marksman\n',
            },
        'Bishop': {
            'class': 'Magician',
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['White Gold Book', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 50, '% watt': 0,
            '# matt': 140, '% matt': 0,
            '# wdef': 550, '% wdef': 0,
            '# mdef': 550, '% mdef': 0,
            '# accuracy': 300, '% accuracy': 0.15,
            '# avoid': 300, '% avoid': 0,
            '# hp': 750, '% hp': 0,
            '# mp': 25950, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0.1,
            '% Ignore Defense': 0.36,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.85,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.6,
            '% Skill Damage': 3.65,
            '% Hyper Reinforce': 0.45,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.1,
            '# Skill Delay': [1],
            'description':'Bishop has the highest amount of supportive skills at their disposal in healing allies, dispelling negative spell effects and buffing their stats. This allows Bishop\'s party members to take on difficult challenges that provides better rewards compared to soloing in activities such as boss raids or to effectively speed up leveling progress.\n\nClass: Magician\nCategory: Explorer\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: White Gold Book, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancedment Route:\nI:Magician -> II.Cleric -> III.Priest -> IV.Bishop\n',
            },
        'Arch Mage (Fire, Poison)': {
            'class': 'Magician',
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['Rusty Book', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 70, '% matt': 0.5,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 25200, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 1,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.2,
            '% Skill Damage': 2.61,
            '% Hyper Reinforce': 1.05,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Fire/Poison Arch Mage currently deals the highest amount of magic damage among all magician classes. They are famous for their high damage skill "Myst Eruption". They are able to poison enemies which deals damage over time and set them ablaze.\n\nClass: Magician\nCategory: Explorer\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: Rusty Book, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancedment Route:\nI:Magician -> II.Wizard (Fire, Poison) -> III.Mage (Fire, Poison) -> IV.Arch Mage (Fire, Poison)\n',
            },
        'Arch Mage (Ice, Lightning)': {
            'class': 'Magician',
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['Metallic Blue Book', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 70, '% matt': 0.5,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 25200, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 1,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.4,
            '% Skill Damage': 3,
            '% Hyper Reinforce': 1.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.25,
            '# Skill Delay': [1],
            'description':'Ice/Lightning Arch Mage deals less damage comparing to Fire/Poison Arch Mage, however they have more defense and utility skills. They are the only Explorer with a bind skill "Freezing Breath". They are able to use freezing skills which slows enemies and increases their damage, and lightning attacks.\n\nClass: Magician\nCategory: Explorer\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: Metallic Blue Book, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancedment Route:\nI:Magician -> II.Wizard (Ice, Lightning) -> III.Mage (Ice, Lightning) -> IV.Arch Mage (Ice, Lightning)\n',
            },
        'Buccaneer': {
            'class': 'Pirate',
            'Weapon': ['Knuckle'],
            'Secondary': ['Wrist Band'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 80, '% watt': 0.15,
            '# matt': 0, '% matt': 0,
            '# wdef': 600, '% wdef': 0,
            '# mdef': 600, '% mdef': 0,
            '# accuracy': 580, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0.2, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 60, '# max speed': 160, '# jump': 23,
            '% mastery': 0.9,
            '% Boss Damage': 0.2,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.5,
            '% Min Crit': 0.4,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 3.2,
            '% Hyper Reinforce': 0.55,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.2,
            '# Skill Delay': [1],
            'description':'Buccaneer is one of Pirate subclass that uses knuckles to knock-down their enemies in close-range combat.\n\nClass: Pirate\nCategory: Explorer\n\nPrimary Weapon: Knuckle\nSecondary Weapon: Wrist Band\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Pirate -> II:Brawler -> III:Marauder -> IV:Buccaneer\n',
            },
        'Corsair': {
            'class': 'Pirate',
            'Weapon': ['Gun'],
            'Secondary': ['Far Sight'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1269, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 30, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0.2,
            '# mdef': 0, '% mdef': 0.2,
            '# accuracy': 120, '% accuracy': 0,
            '# avoid': -300, '% avoid': 0,
            '# hp': 600, '% hp': 0.4,
            '# mp': 600, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 60, '# max speed': 160, '# jump': 23,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.2,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.4,
            '% Max Crit': 0.6,
            '% Status Resistance': 0.45,
            '% Skill Damage': 3,
            '% Hyper Reinforce': 0.55,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Corsair is one of Pirate subclass that uses guns to shoot down their enemies in long-range combat.\n\nClass: Pirate\nCategory: Explorer\n\nPrimary Weapon: Gun\nSecondary Weapon: Far Sight\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancement Route:\nI:Pirate -> II:Gunslinger -> III:Outlaw -> IV:Corsair\n',
            },
        'Cannoneer': {
            'class': 'Pirate',
            'Weapon': ['Cannon'],
            'Secondary': ['Powder Keg'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 50, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 250, '% wdef': 0.5,
            '# mdef': 250, '% mdef': 0.5,
            '# accuracy': 370, '% accuracy': 0,
            '# avoid': 250, '% avoid': 0,
            '# hp': 1000, '% hp': 0.25,
            '# mp': 1000, '% mp': 0.05,
            '# all stats': 75, '% all stats': 0,
            '# speed': 15, '# max speed': 140, '# jump': 10,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.6,
            '% Final Damage': 0,
            '% Crit Rate': 0.55,
            '% Min Crit': 0.3,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.2,
            '% Skill Damage': 3.6,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.2,
            '% Hyper Critical': 0.3,
            '# Skill Delay': [1],
            'description':'Cannoneer is a special Explorer who uses Cannon aided with by a monkey companion.\n\nClass: Pirate\nCategory: Explorer\n\nPrimary Weapon: Cannon\nSecondary Weapon: Powder Keg\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Pirate -> II:Cannoneer -> III:Cannon Trooper -> IV:Cannon Master\n',
            },
        'Night Lord': {
            'class': 'Thief',
            'Weapon': ['Claw'],
            'Secondary': ['Charm'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1269, '% luk': 0,
            '# watt': 70, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 340, '% accuracy': 0,
            '# avoid': 220, '% avoid': 0,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 20,
            '% mastery': 0.85,
            '% Boss Damage': 0.1,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.25,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.45,
            '% Max Crit': 0.75,
            '% Status Resistance': 0.3,
            '% Skill Damage': 3.78,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.37,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Night Lords are users of claws and stars. Most of their skills focus on 1 target which is great for boss raids.\n\nClass: Thief\nCategory: Explorer\n\nPrimary Weapon: Claw\nSecondary Weapon: Charm\nPrimary Stat: LUK\nSecondary Stat: STR, DEX\n\nAdvancement Route:\nI:Thief -> II:Assassin -> III:Hermit -> IV:Night Lord\n',
            },
        'Shadower': {
            'class': 'Thief',
            'Weapon': ['Dagger'],
            'Secondary': ['Dagger Scabbard', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1269, '% luk': 0,
            '# watt': 160, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 1.1,
            '# mdef': 0, '% mdef': 1.1,
            '# accuracy': 340, '% accuracy': 0,
            '# avoid': 220, '% avoid': 0.2,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 20,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.35,
            '% Max Crit': 0.65,
            '% Status Resistance': 0.3,
            '% Skill Damage': 6.27,
            '% Hyper Reinforce': 0.7,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Possessing extremely unique skills themed around meso use, shadow abuse, and flashy dagger acrobatics, Shadowers enjoy high damage and very high defense.\n\nClass: Thief\nCategory: Explorer\n\nPrimary Weapon: Dagger\nSecondary Weapon: Dagger Scabbard, Shield\nPrimary Stat: LUK\nSecondary Stat: STR, DEX\n\nAdvancement Route:\nI:Thief -> II:Bandit -> III:Chief Bandit -> IV:Shadower\n',
            },
        'Blade Master': {
            'class': 'Thief',
            'Weapon': ['Dagger'],
            'Secondary': ['Katara'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1269, '% luk': 0,
            '# watt': 105, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0.6,
            '# mdef': 0, '% mdef': 0.6,
            '# accuracy': 120, '% accuracy': 0.15,
            '# avoid': 0, '% avoid': 0.55,
            '# hp': 0.2, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 23,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0.6,
            '% Crit Rate': 0.4,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 2.4,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.44,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'As a part of the covert organization located in the Secret Garden hidden in Kerning City, the Dual Blades have their own agendas put them at odds with regular Explorer Thieves. Dual Blades move in a flash across battlefield while wielding two weapons: a dagger in one hand and a katara in the other. Their skills grant them high evasion, the ability to sneak past foes, mobility and the ability to link special combos.\n\nClass: Thief\nCategory: Explorer\n\nPrimary Weapon: Dagger\nSecondary Weapon: Katara\nPrimary Stat: LUK\nSecondary Stat: STR, DEX\n\nAdvancement Route:\nI:Rogue -> II:Blade Recruit -> III:Blade Acolyte -> IV:Blade Specialist -> V:Blade Master\n',
            },
        'Hero': {
            'class': 'Warrior',
            'Weapon': ['One-handed Sword', 'Two-handed Sword', 'One-handed Axe', 'Two-handed Axe'],
            'Secondary': ['Medallion', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 80, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 200, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0.1,
            '# avoid': 0, '% avoid': 0,
            '# hp': 4200, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 10, '# max speed': 150, '# jump': 10,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.5,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.6,
            '% Final Damage': 0,
            '% Crit Rate': 0.35,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 2.68,
            '% Hyper Reinforce': 1.75,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Heroes specialize in swords and axes, they can also use shields. They utilize combo strikes to create powerful blows to shake the enemy.\n\nClass: Warrior\nCategory: Explorer\n\nPrimary Weapon: One-handed Sword, Two-handed Sword, One-handed Axe, Two-handed Axe\nSecondary Weapon: Medallion, Shield\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Swordman -> II:Fighter -> III:Crusader -> IV:Hero\n',
            },
        'Paladin': {
            'class': 'Warrior',
            'Weapon': ['One-handed Sword', 'Two-handed Sword', 'One-handed Mace', 'Two-handed Mace'],
            'Secondary': ['Rosary', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 110, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 600, '% wdef': 2.3,
            '# mdef': 0, '% mdef': 2.3,
            '# accuracy': 120, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 4200, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 10, '# max speed': 150, '# jump': 10,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.3,
            '% Final Damage': 0,
            '% Crit Rate': 0.15,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.5,
            '% Skill Damage': 3.18,
            '% Hyper Reinforce': 0.85,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.6,
            '% Hyper Critical': 0.6,
            '# Skill Delay': [1],
            'description':'Paladins are armed with swords, maces, and shields, with the best defense abilities. They utilize the power of fire, ice, lightning, and holy elements to scar the battlefield.\n\nClass: Warrior\nCategory: Explorer\n\nPrimary Weapon: One-handed Sword, Two-handed Sword, One-handed Mace, Two-handed Mace\nSecondary Weapon: Rosary, Shield\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Swordman -> II:Page -> III:White Knight -> IV:Paladin\n',
            },
        'Dark Knight': {
            'class': 'Warrior',
            'Weapon': ['Spear', 'Polearm'],
            'Secondary': ['Iron Chain'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 70, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 1000, '% wdef': 0,
            '# mdef': 700, '% mdef': 0,
            '# accuracy': 540, '% accuracy': 0,
            '# avoid': 300, '% avoid': 0,
            '# hp': 4200, '% hp': 0.8,
            '# mp': 0, '% mp': 0.6,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 150, '# jump': 10,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.3,
            '% Final Damage': 0.8,
            '% Crit Rate': 0.85,
            '% Min Crit': 0.85,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.2,
            '% Skill Damage': 3.12,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.44,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'Dark Knights are vampire warriors who utilize Spear or Polearm to attack their enemy. Their skills are heavily dependant on their HP, with incredible survivability.\n\nClass: Warrior\nCategory: Explorer\n\nPrimary Weapon: Spear, Polearm\nSecondary Weapon: Iron Chain\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Swordman -> II:Spearman -> III:Berserker -> IV:Dark Knight\n',
            },

        'dummy': {
            'class': 'dummy',
            'Weapon': ['dummy'],
            'Secondary': ['dummy'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1239, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.15,
            '% Min Crit': 0.2,
            '% Max Crit': 0.5,
            '% Status Resistance': 0,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'\n\nClass: Thief, Pirate\nCategory: Resistance\n\nPrimary Weapon: Whip Blade\nSecondary Weapon: Core Controller\nPrimary Stat: STR, DEX, LUK\n\nAdvancement Route:\nI:Xenon -> II:Xenon -> III:Xenon -> IV:Xenon\n',
            },
        'Xenon': {
            'class': 'Thief, Pirate',
            'Weapon': ['Whip Blade'],
            'Secondary': ['dummy'],
            'Emblem': ['dummy'],
            '# str': 1239, '% str': 0,
            '# dex': 1239, '% dex': 0,
            '# int': 1239, '% int': 0,
            '# luk': 1239, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.05,
            '% Min Crit': 0.2,
            '% Max Crit': 0.5,
            '% Status Resistance': 0,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0,
            '# Skill Delay': [1],
            'description':'Xenon is a member of the Resistance. He is a mixture of Thief and Pirate, therefore using Strength, Dexterity, and Luck as his main stats. With a Whip Blade and a Controller, Xenon uses technology and quick-paced attacks to eliminate his enemies. Originally a weapon created by Gelimer, Xenon escaped and joined the Resistance.\n\nClass: Thief, Pirate\nCategory: Resistance\n\nPrimary Weapon: Whip Blade\nSecondary Weapon: Core Controller\nPrimary Stat: STR, DEX, LUK\n\nAdvancement Route:\nI:Xenon -> II:Xenon -> III:Xenon -> IV:Xenon\n',
            },
        }
    m_weaponMultiplier = {
        'None': 0,
        'One-handed Sword': 1.2,
        'Two-handed Sword': 1.34,
        'One-handed Axe': 1.2,
        'Two-handed Axe': 1.34,
        'One-handed Mace': 1.2,
        'Two-handed Mace': 1.34,
        'Spear': 1.49,
        'Polearm': 1.49,
        'Wand': [1.2, 1],
        'Staff': [1.2, 1],
        'Bow': 1.3,
        'Crossbow': 1.35,
        'Claw': 1.75,
        'Dagger': 1.3,
        'Gun': 1.5,
        'Knuckle': 1.7,
        'Katara': 1.3,
        'Cane': 1.3,
        'Whip Blade': 1.5,
        'Desperado': 1.3,
        'Shining Rod': 1.2,
        'Cannon': 1.8,
        'Soul Shooter': 1.7,
        'Katana': 1.25,
        'Fan': 1.35,
        'Long Sword': 1.34,
        'Great Sword': 1.49,
        'Dual Bowguns': 1.32,
        }

if __name__ == '__main__':
    print JobLib.m_job['Bow Master'].keys()
        
            
