class JobLib:

# 0 - Explorer
# 1 - Cygnus Knights
# 2 - Hero
# 3 - Resistance
# 4 - Others

    m_job = {
        'Bow Master': {
            'class': 'Bowman',
            'category': 0,
            'Weapon': ['Bow'],
            'Secondary': ['Arrow Fletching'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1309, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 120, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': -0.1,
            '# mdef': 0, '% mdef': -0.1,
            '# accuracy': 345, '% accuracy': 0.35,
            '# avoid': 225, '% avoid': 0.3,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 160, '# jump': 0,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2875,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.55,
            '% Final Damage': 0,
            '% Crit Rate': 0.8,
            '% Min Crit': 0.35,
            '% Max Crit': 0.8,
            '% Status Resistance': 0.2,
            '% Skill Damage': 1.95,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.1,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            'Hyper related': ['Hurricane - Reinforce', 'Hurricane - Boss Rush'],
            '# Skill Delay': [1],
            'description':'Explorers specialized in using bows. Bow Masters are well-known for their high hits per second with "Hurricane" and "Arrow Platter".\n\nClass: Bowman\nCategory: Explorer\n\nPrimary Weapon: Bow\nSecondary Weapon: Arrow Fletching\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancement Route:\nI:Archer -> II:Hunter -> III:Ranger -> IV:Bow Master\n',
            },
        'Marksman': {
            'class': 'Bowman',
            'category': 0,
            'Weapon': ['Crossbow'],
            'Secondary': ['Bow Thimble'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1309, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 60, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0.3,
            '# mdef': 0, '% mdef': 0.3,
            '# accuracy': 345, '% accuracy': 0.25,
            '# avoid': 225, '% avoid': -0.5,
            '# hp': 0, '% hp': 0.4,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 160, '# jump': 0,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2875,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.15,
            '% Final Damage': 0,
            '% Crit Rate': 0.8,
            '% Min Crit': 0.2,
            '% Max Crit': 1.2,
            '% Status Resistance': 0.2,
            '% Skill Damage': 44.1,
            '% Hyper Reinforce': 0.8,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.6,
            '% Hyper Critical': 1,
            'Hyper related': ['Snipe', 'Vital Hunter', 'Snipe - Reinforce', 'Bolt Surplus', 'Last Man Standing'],
            '# Skill Delay': [1],
            'description':'Explorers specialized in using crossbows. Marksmans are well-known for their single-line high damage skill "Snipe", which has a damage cap of 400,000,000.\n\nClass: Bowman\nCategory: Explorer\n\nPrimary Weapon: Crossbow\nSecondary Weapon: Bow Thimble\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancedment Route:\nI:Archer -> II.Crossbowman -> III.Sniper -> IV.Marksman\n',
            },
        'Bishop': {
            'class': 'Magician',
            'category': 0,
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['White Gold Book', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 50, '% watt': 0,
            '# matt': 140, '% matt': 0,
            '# wdef': 550, '% wdef': 0,
            '# mdef': 550, '% mdef': 0,
            '# accuracy': 300, '% accuracy': 0.15,
            '# avoid': 300, '% avoid': 0,
            '# hp': 750, '% hp': 0,
            '# mp': 25950, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0.1,
            '% Ignore Defense': 0.36,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.85,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.6,
            '% Skill Damage': 3.65,
            '% Hyper Reinforce': 0.45,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Arcane Aim', 'Blessed Harmony'],
            'description':'Bishop has the highest amount of supportive skills at their disposal in healing allies, dispelling negative spell effects and buffing their stats. This allows Bishop\'s party members to take on difficult challenges that provides better rewards compared to soloing in activities such as boss raids or to effectively speed up leveling progress.\n\nClass: Magician\nCategory: Explorer\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: White Gold Book, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancedment Route:\nI:Magician -> II.Cleric -> III.Priest -> IV.Bishop\n',
            },
        'Arch Mage (Fire, Poison)': {
            'class': 'Magician',
            'category': 0,
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['Rusty Book', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 70, '% matt': 0.5,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 25200, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 1,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.2,
            '% Skill Damage': 2.61,
            '% Hyper Reinforce': 1.05,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Burning Magic', 'Fervent Drain', 'Arcane Aim', 'Paralyze - Reinforce'],
            'description':'Fire/Poison Arch Mage currently deals the highest amount of magic damage among all magician classes. They are famous for their high damage skill "Myst Eruption". They are able to poison enemies which deals damage over time and set them ablaze.\n\nClass: Magician\nCategory: Explorer\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: Rusty Book, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancedment Route:\nI:Magician -> II.Wizard (Fire, Poison) -> III.Mage (Fire, Poison) -> IV.Arch Mage (Fire, Poison)\n',
            },
        'Arch Mage (Ice, Lightning)': {
            'class': 'Magician',
            'category': 0,
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['Metallic Blue Book', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 70, '% matt': 0.5,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 25200, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 1,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.4,
            '% Skill Damage': 3,
            '% Hyper Reinforce': 1.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.25,
            '# Skill Delay': [1],
            'Hyper related': ['Storm Magic', 'Chain Lightning', 'Arcane Aim', 'Frost Clutch', 'Chain Lightning - Reinforce'],
            'description':'Ice/Lightning Arch Mage have excellent mobbing, some defense and utility skills, and also good damage. They are the only Explorer with a bind skill "Freezing Breath". They are able to use freezing skills which slows enemies and increases their damage, and lightning attacks.\n\nClass: Magician\nCategory: Explorer\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: Metallic Blue Book, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancedment Route:\nI:Magician -> II.Wizard (Ice, Lightning) -> III.Mage (Ice, Lightning) -> IV.Arch Mage (Ice, Lightning)\n',
            },
        'Buccaneer': {
            'class': 'Pirate',
            'category': 0,
            'Weapon': ['Knuckle'],
            'Secondary': ['Wrist Band'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 80, '% watt': 0.15,
            '# matt': 0, '% matt': 0,
            '# wdef': 600, '% wdef': 0,
            '# mdef': 600, '% mdef': 0,
            '# accuracy': 580, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0.2, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 60, '# max speed': 160, '# jump': 23,
            '% mastery': 0.9,
            '% Boss Damage': 0.2,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.5,
            '% Min Crit': 0.4,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 3.2,
            '% Hyper Reinforce': 0.55,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.2,
            'Hyper related': ['Octopunch - Boss Rush', 'Octopunch - Reinforce', 'Octopunch', 'Pirate\' Revenge', 'Precision Strikes'],
            '# Skill Delay': [1],
            'description':'Buccaneer is one of Pirate subclass that uses knuckles to knock-down their enemies in close-range combat.\n\nClass: Pirate\nCategory: Explorer\n\nPrimary Weapon: Knuckle\nSecondary Weapon: Wrist Band\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Pirate -> II:Brawler -> III:Marauder -> IV:Buccaneer\n',
            },
        'Corsair': {
            'class': 'Pirate',
            'category': 0,
            'Weapon': ['Gun'],
            'Secondary': ['Far Sight'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1269, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 30, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0.2,
            '# mdef': 0, '% mdef': 0.2,
            '# accuracy': 120, '% accuracy': 0,
            '# avoid': -300, '% avoid': 0,
            '# hp': 600, '% hp': 0.4,
            '# mp': 600, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 60, '# max speed': 160, '# jump': 23,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.2,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.4,
            '% Max Crit': 0.6,
            '% Status Resistance': 0.45,
            '% Skill Damage': 3,
            '% Hyper Reinforce': 0.55,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            'Hyper related': ['Rapid Fire - Reinforce', 'Rapid Fire - Boss Rush', 'Pirate\'s Revenge', 'Parrotargetting'],
            '# Skill Delay': [1],
            'description':'Corsair is one of Pirate subclass that uses guns to shoot down their enemies in long-range combat.\n\nClass: Pirate\nCategory: Explorer\n\nPrimary Weapon: Gun\nSecondary Weapon: Far Sight\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancement Route:\nI:Pirate -> II:Gunslinger -> III:Outlaw -> IV:Corsair\n',
            },
        'Cannoneer': {
            'class': 'Pirate',
            'category': 0,
            'Weapon': ['Cannon'],
            'Secondary': ['Powder Keg'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 50, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 250, '% wdef': 0.5,
            '# mdef': 250, '% mdef': 0.5,
            '# accuracy': 370, '% accuracy': 0,
            '# avoid': 250, '% avoid': 0,
            '# hp': 1000, '% hp': 0.25,
            '# mp': 1000, '% mp': 0.05,
            '# all stats': 75, '% all stats': 0,
            '# speed': 15, '# max speed': 140, '# jump': 10,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.6,
            '% Final Damage': 0,
            '% Crit Rate': 0.55,
            '% Min Crit': 0.3,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.2,
            '% Skill Damage': 3.6,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.2,
            '% Hyper Critical': 0.3,
            'Hyper related': ['Cannon Barrage', 'Cannon Barrage  - Reinforce', 'Cannon Barrage - Critical Chance'],
            '# Skill Delay': [1],
            'description':'Cannoneer is a special Explorer who uses Cannon aided with by a monkey companion.\n\nClass: Pirate\nCategory: Explorer\n\nPrimary Weapon: Cannon\nSecondary Weapon: Powder Keg\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Pirate -> II:Cannoneer -> III:Cannon Trooper -> IV:Cannon Master\n',
            },
        'Night Lord': {
            'class': 'Thief',
            'category': 0,
            'Weapon': ['Claw'],
            'Secondary': ['Charm'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1269, '% luk': 0,
            '# watt': 70, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 340, '% accuracy': 0,
            '# avoid': 220, '% avoid': 0,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 20,
            '% mastery': 0.85,
            '% Boss Damage': 0.1,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.25,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.45,
            '% Max Crit': 0.75,
            '% Status Resistance': 0.3,
            '% Skill Damage': 3.78,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.37,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Quad Star - Reinforce', 'Quad Star - Boss Rush', 'Frailty Curse', 'Frailty Curse - Enhance'],
            'description':'Night Lords are users of claws and stars. Most of their skills focus on single target, making them great for boss raids.\n\nClass: Thief\nCategory: Explorer\n\nPrimary Weapon: Claw\nSecondary Weapon: Charm\nPrimary Stat: LUK\nSecondary Stat: STR, DEX\n\nAdvancement Route:\nI:Thief -> II:Assassin -> III:Hermit -> IV:Night Lord\n',
            },
        'Shadower': {
            'class': 'Thief',
            'category': 0,
            'Weapon': ['Dagger'],
            'Secondary': ['Dagger Scabbard', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1269, '% luk': 0,
            '# watt': 160, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 1.1,
            '# mdef': 0, '% mdef': 1.1,
            '# accuracy': 340, '% accuracy': 0,
            '# avoid': 220, '% avoid': 0.2,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 20,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.2,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.35,
            '% Max Crit': 0.65,
            '% Status Resistance': 0.3,
            '% Skill Damage': 6.27,
            '% Hyper Reinforce': 0.7,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.5,
            '# Skill Delay': [1],
            'Hyper related': ['Assassinate - Reinforce', 'Assassinate - Boss Rush', 'Flip of the Coin', 'Boomerang Stab'],
            'description':'Possessing extremely unique skills themed around meso use, shadow abuse, and flashy dagger acrobatics, Shadowers enjoy high damage and very high defense.\n\nClass: Thief\nCategory: Explorer\n\nPrimary Weapon: Dagger\nSecondary Weapon: Dagger Scabbard, Shield\nPrimary Stat: LUK\nSecondary Stat: STR, DEX\n\nAdvancement Route:\nI:Thief -> II:Bandit -> III:Chief Bandit -> IV:Shadower\n',
            },
        'Blade Master': {
            'class': 'Thief',
            'category': 0,
            'Weapon': ['Dagger'],
            'Secondary': ['Katara'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1269, '% luk': 0,
            '# watt': 105, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0.6,
            '# mdef': 0, '% mdef': 0.6,
            '# accuracy': 120, '% accuracy': 0.15,
            '# avoid': 0, '% avoid': 0.55,
            '# hp': 0.2, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 23,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0.6,
            '% Crit Rate': 0.4,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 2.4,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.44,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Phantom Blow', 'Phantom Blow - Reinforce', 'Phantom Blow - Guardbreak'],
            'description':'As a part of the covert organization located in the Secret Garden hidden in Kerning City, the Dual Blades have their own agendas put them at odds with regular Explorer Thieves. Dual Blades move in a flash across battlefield while wielding two weapons: a Dagger in one hand and a Katara in the other. Their skills grant them high evasion, the ability to sneak past foes, mobility and the ability to link special combos.\n\nClass: Thief\nCategory: Explorer\n\nPrimary Weapon: Dagger\nSecondary Weapon: Katara\nPrimary Stat: LUK\nSecondary Stat: STR, DEX\n\nAdvancement Route:\nI:Rogue -> II:Blade Recruit -> III:Blade Acolyte -> IV:Blade Specialist -> V:Blade Master\n',
            },
        'Hero': {
            'class': 'Warrior',
            'category': 0,
            'Weapon': ['One-handed Sword', 'Two-handed Sword', 'One-handed Axe', 'Two-handed Axe'],
            'Secondary': ['Medallion', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 80, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 200, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0.1,
            '# avoid': 0, '% avoid': 0,
            '# hp': 4200, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 10, '# max speed': 150, '# jump': 10,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.5,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.6,
            '% Final Damage': 0,
            '% Crit Rate': 0.35,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 2.68,
            '% Hyper Reinforce': 1.75,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Advanced Combo', 'Advanced Combo - Boss Rush', 'Advanced Combo - Reinforce', 'Raging Blow - Reinforce', 'Raging Blow', 'Chance Attack'],
            'description':'Heroes specialize in swords and axes, they can also use shields. They utilize combo strikes to create powerful blows to shake the enemy.\n\nClass: Warrior\nCategory: Explorer\n\nPrimary Weapon: One-handed Sword, Two-handed Sword, One-handed Axe, Two-handed Axe\nSecondary Weapon: Medallion, Shield\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Swordman -> II:Fighter -> III:Crusader -> IV:Hero\n',
            },
        'Paladin': {
            'class': 'Warrior',
            'category': 0,
            'Weapon': ['One-handed Sword', 'Two-handed Sword', 'One-handed Mace', 'Two-handed Mace'],
            'Secondary': ['Rosary', 'Shield'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 110, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 600, '% wdef': 2.3,
            '# mdef': 0, '% mdef': 2.3,
            '# accuracy': 120, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 4200, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 10, '# max speed': 150, '# jump': 10,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.3,
            '% Final Damage': 0,
            '% Crit Rate': 0.15,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.5,
            '% Skill Damage': 3.18,
            '% Hyper Reinforce': 0.85,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.6,
            '% Hyper Critical': 0.6,
            '# Skill Delay': [1],
            'Hyper related': ['Blast - Reinforce', 'Blast - Critical Chance', 'Blast', 'Advanced Charge', 'Threaten', 'Threaten - Enhance'],
            'description':'Paladins are armed with swords, maces, and shields, with the best defense abilities. They utilize the power of fire, ice, lightning, and holy elements to scar the battlefield.\n\nClass: Warrior\nCategory: Explorer\n\nPrimary Weapon: One-handed Sword, Two-handed Sword, One-handed Mace, Two-handed Mace\nSecondary Weapon: Rosary, Shield\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Swordman -> II:Page -> III:White Knight -> IV:Paladin\n',
            },
        'Dark Knight': {
            'class': 'Warrior',
            'category': 0,
            'Weapon': ['Spear', 'Polearm'],
            'Secondary': ['Iron Chain'],
            'Emblem': ['Explorer', 'Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 70, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 1000, '% wdef': 0,
            '# mdef': 700, '% mdef': 0,
            '# accuracy': 540, '% accuracy': 0,
            '# avoid': 300, '% avoid': 0,
            '# hp': 4200, '% hp': 0.8,
            '# mp': 0, '% mp': 0.6,
            '# all stats': 0, '% all stats': 0,
            '# speed': 30, '# max speed': 150, '# jump': 10,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.3,
            '% Final Damage': 0.8,
            '% Crit Rate': 0.85,
            '% Min Crit': 0.85,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.2,
            '% Skill Damage': 3.12,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.44,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Gungnir\'s Descent - Boss Rush', 'Gungnir\'s Descent - Reinforce', 'Gungnir\'s Descent - Guardbreak', 'Gungnir\'s Descent'],
            'description':'Dark Knights are vampire warriors who utilize Spear or Polearm to attack their enemy. Their skills are heavily dependant on their HP, with incredible survivability.\n\nClass: Warrior\nCategory: Explorer\n\nPrimary Weapon: Spear, Polearm\nSecondary Weapon: Iron Chain\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Swordman -> II:Spearman -> III:Berserker -> IV:Dark Knight\n',
            },

        'Blaze Wizard': {
            'class': 'Magician',
            'category': 1,
            'Weapon': ['Wand'],
            'Secondary': ['Jewel'],
            'Emblem': ['Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1404, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 80, '% matt': 0,
            '# wdef': 0, '% wdef': 0.15,
            '# mdef': 0, '% mdef': 0.15,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 25200, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 1,
            '% Total Damage': 0.25,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.45,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.4,
            '% Skill Damage': 2.8,
            '% Hyper Reinforce': 0.2+0.5,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.2,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Orbital Flame - Reinforce', 'Orbital Flame - Guardbreak', 'Burning Conduit'],
            'description':'The magician branch of the Cygnus Knights, Blaze Wizards wield wild and potent fire magic. As a Cygnus Knight, they are able to call forth the Elements to help them in battle. Blaze Wizards are led by the Chief Knight of Fire: Oz, who resides on Empress\'s Road in Ereve.\n\nClass: Magician\nCategory: Cygnus Knight\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: Jewel, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancement Route:\nI:Blaze Wizard -> II:Blaze Wizard -> III:Blaze Wizard -> IV:Blaze Wizard\n',
            },

        'Dawn Warrior': {
            'class': 'Warrior',
            'category': 1,
            'Weapon': ['One-handed Sword', 'Two-handed Sword'],
            'Secondary': ['Jewel', 'Shield'],
            'Emblem': ['Boss Arena'],
            '# str': 1424, '% str': 0,
            '# dex': 24, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 170, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 2500, '% wdef': 0,
            '# mdef': 2500, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0.5,
            '# avoid': 0, '% avoid': 0,
            '# hp': 2000, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 30, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 20,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.49,
            '% Ignore Resistance': 0.7,
            '% Total Damage': 0.4,
            '% Final Damage': 0,
            '% Crit Rate': 0.6,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.3,
            '% Skill Damage': 3.16,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Crescent Divide/Solar Pierce - Reinforce'],
            'description':'Dawn Warriors are champions that boast powerful offensive strength. Not just a plain warrior, they use the power of the sun and the moon to enhance their weapons. Dawn Warriors are led by the Chief Knight of Light: Mihile, who resides on Empress\'s Road in Ereve.\n\nClass: Warrior\nCategory: Cygnus Knight\n\nPrimary Weapon: One-handed Sword, Two-handed Sword\nSecondary Weapon: Jewel, Shield\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Dawn Warrior -> II:Dawn Warrior -> III:Dawn Warrior -> IV:Dawn Warrior\n',
            },
        'Mihile': {
            'class': 'Warrior',
            'category': 1,
            'Weapon': ['One-handed Sword'],
            'Secondary': ['Soul Shield'],
            'Emblem': ['Boss Arena'],
            '# str': 1329, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 110, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 3,
            '# mdef': 0, '% mdef': 2,
            '# accuracy': 320, '% accuracy': 0.1,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0.4,
            '# mp': 0, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 25, '# max speed': 140, '# jump': 20,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.4,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.9,
            '% Final Damage': 0,
            '% Crit Rate': 0.35,
            '% Min Crit': 0.5,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.6,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0.4,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0.2,
            'Hyper related': ['Four-Point Assault - Reinforce', 'Righteous Indignation'],
            '# Skill Delay': [1],
            'description':'Mihile is a special branch of Cygnus Knights and is the trainer of the Dawn Warriors. Mihile possesses a special shield, known as the Soul Shield.\nOriginally an average boy working in a store, Cygnus revealed that he possessed an extraordinary power within him: the power of Light. Now named Mihile, his true destiny is to use his power for the greater good and defeat the evil that wavers in the Maple World.\n\nClass: Warrior\nCategory: Cygnus Knight\n\nPrimary Weapon: One-handed Sword\nSecondary Weapon: Soul Shield\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Mihile -> II:Mihile -> III:Mihile -> IV:Mihile\n',
            },
        'Night Walker': {
            'class': 'Thief',
            'category': 1,
            'Weapon': ['Claw'],
            'Secondary': ['Jewel'],
            'Emblem': ['Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1404, '% luk': 0,
            '# watt': 60, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0.15,
            '# hp': 7000, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 160, '# jump': 20,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.15,
            '% Ignore Resistance': 0.5,
            '% Total Damage': 0.2,
            '% Final Damage': 0,
            '% Crit Rate': 0.5,
            '% Min Crit': 0.45,
            '% Max Crit': 0.75,
            '% Status Resistance': 0.6,
            '% Skill Damage': 3.6,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.1,
            '% Hyper Guard Break': 0.35,
            '% Hyper Critical': 0.2,
            '# Skill Delay': [1],
            'Hyper related': ['Quintuple Star - Reinforce', 'Quintuple Star - Boss Rush', 'Quintuple Star - Critical Chance', 'Adaptive Darkness'],
            'description':'Night Walkers are Cygnus Knights who specializes in the art of assassinating enemies. Marked and assisted by the spirit of Darkness, Umbra, Night Walkers serve justice in places where Light does not reach.\n\nClass: Thief\nCategory: Cygnus Knight\n\nPrimary Weapon: Claw\nSecondary Weapon: Jewel\nPrimary Stat: LUK\nSecondary Stat: DEX, STR\n\nAdvancement Route:\nI:Night Walker -> II:Night Walker -> III:Night Walker -> IV:Night Walker\n',
            },
        'Thunder Breaker': {
            'class': 'Pirate',
            'category': 1,
            'Weapon': ['Knuckle'],
            'Secondary': ['Jewel'],
            'Emblem': ['Boss Arena'],
            '# str': 1404, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 80, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 180, '# jump': 20,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0.5,
            '% Total Damage': 0.85,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.35,
            '% Max Crit': 0.8,
            '% Status Resistance': 0.4,
            '% Skill Damage': 2.5,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.56,
            '% Hyper Critical': 0,
            'Hyper related': ['Annihilate - Reinforce', 'Annihilate - Boss Rush', 'Annihilate - Guardbreak', 'Lightning Elemental', 'Extreme Blitz'],
            '# Skill Delay': [1],
            'description':'Thunder Breakers are Pirates who are christened under Cygnus, blessed by the spirit of lightning and the sea. As Cygnus Knights who study and serve under the direct command of Hawkeye, they use knuckles as their main weapons and can fight at close to fairly long range, using lightning and thunder based techniques which they manipulate using a variety of methods, including most recently, incorporating the shape, nature and influence of the sea.\n\nClass: Pirate\nCategory: Cygnus Knight\n\nPrimary Weapon: Knuckle\nSecondary Weapon: Jewel\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Thunder Breaker -> II:Thunder Breaker -> III:Thunder Breaker -> IV:Thunder Breaker\n',
            },
        'Wind Archer': {
            'class': 'Bowman',
            'category': 1,
            'Weapon': ['Bow'],
            'Secondary': ['Jewel'],
            'Emblem': ['Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1374, '% dex': 0.12,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 120, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 1000, '% wdef': 0,
            '# mdef': 1000, '% mdef': 0,
            '# accuracy': 520, '% accuracy': 0.3,
            '# avoid': 400, '% avoid': 0.3,
            '# hp': 1500, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 35, '# max speed': 160, '# jump': 15,
            '% mastery': 0.85,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.15,
            '% Ignore Resistance': 0.5,
            '% Total Damage': 0.35,
            '% Final Damage': 0,
            '% Crit Rate': 0.7,
            '% Min Crit': 0.35,
            '% Max Crit': 0.8,
            '% Status Resistance': 0.35,
            '% Skill Damage': 3.75,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.28,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Song of Heaven - Reinforce', 'Song of Heaven - Guardbreak', 'Song of Heaven - Boss Rush', 'Emerald Dust'],
            'description':'Wind Archer is the bowman branch of Cygnus Knights. Wind Archers use nature and wind based attacks.\n\nClass: Bowman\nCategory: Cygnus Knight\n\nPrimary Weapon: Bow\nSecondary Weapon: Jewel\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancement Route:\nI:Wind Archer -> II:Wind Archer -> III:Wind Archer -> IV:Wind Archer\n',
            },
        
        'Aran': {
            'class': 'Warrior',
            'category': 2,
            'Weapon': ['Polearm'],
            'Secondary': ['Mass'],
            'Emblem': ['Boss Arena'],
            '# str': 1269, '% str': 0,
            '# dex': 34, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 195, '% watt': 0,
            '# matt': 30, '% matt': 0,
            '# wdef': 775, '% wdef': 0,
            '# mdef': 775, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0.1,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 45, '# max speed': 160, '# jump': 0,
            '% mastery': 0.9,
            '% Boss Damage': 0.2,
            '% Ignore Defense': 0.4,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.35,
            '% Final Damage': 0,
            '% Crit Rate': 0.65,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.6,
            '% Skill Damage': 3.55,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.36,
            '% Hyper Critical': 1,
            '# Skill Delay': [1],
            'Hyper related': ['Final Blow - Reinforce', 'Final Blow - Guardbreak', 'Final Blow'],
            'description':'Aran is one of the six Heroes who sealed away the Black Mage and is part of the Warrior branch. With a Polearm in hand, Aran uses many ice and combination attacks against her foes.\n\nClass: Warrior\nCategory: Hero\n\nPrimary Weapon: Polearm\nSecondary Weapon: Mass\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Aran -> II:Aran -> III:Aran -> IV:Aran\n',
            },
        'Evan': {
            'class': 'Magician',
            'category': 2,
            'Weapon': ['Wand', 'Staff'],
            'Secondary': ['Document', 'Shield'],
            'Emblem': ['Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1279, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 105, '% matt': 0.85,
            '# wdef': 995, '% wdef': 0,
            '# mdef': 1095, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0.2,
            '# hp': 0, '% hp': 0.1,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 10, '# max speed': 140, '# jump': 0,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 1,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.55,
            '% Min Crit': 0.5,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.15,
            '% Skill Damage': 4.5,
            '% Hyper Reinforce': 0.2,
            '% Hyper Boss Rush': 0.3,
            '% Hyper Guard Break': 0.36,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Illusion', 'Illusion - Guardbreak', 'Illusion - Reinforce'],
            'description':'Evan is a Magician-type Hero class aided with by a legendary Onyx Dragon.\nOnce, there was a normal boy that lived near the village of Henesys. In a field, he discovered a dragon egg that he saw in his dreams. It turns out that he is part of an ancient line of Dragon Masters that was nearly wiped out by the Black Mage who was sealed by the legendary Heroes. And so, the story of Evan the Dragon Master unfolds.\n\nClass: Magician\nCategory: Hero\n\nPrimary Weapon: Wand, Staff\nSecondary Weapon: Document, Shield\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancement Route:\nI:Evan -> II:Evan -> III:Evan -> IV:Evan\n',
            },
        'Luminous': {
            'class': 'Magician',
            'category': 2,
            'Weapon': ['Shining Rod'],
            'Secondary': ['Light Orb'],
            'Emblem': ['Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 1299, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 110, '% matt': 0.05,
            '# wdef': 450, '% wdef': 0,
            '# mdef': 450, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 25200, '% mp': 0.3,
            '# all stats': 0, '% all stats': 0,
            '# speed': 20, '# max speed': 140, '# jump': 10,
            '% mastery': 0.95,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.52,
            '% Ignore Resistance': 1,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.45,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.4,
            '% Skill Damage': 3.33,
            '% Hyper Reinforce': 0.5,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 1,
            '# Skill Delay': [1],
            'Hyper related': ['Ender', 'Ender - Reinforce', 'Dark Crescendo'],
            'description':'Luminous is one of the six Heroes who sealed away the Black Mage and is part of the Magician branch. He uses a Shining Rod and an Orb for his weapons.\nAs the last of the six legendary Heroes, Luminous dealt the final blow to the Black Mage once and for all. However, upon doing so, he became tainted with the Black Mage\'s Dark power. He wields the power of both Light and Dark, and reaches his maximum potential in the state of Equilibrium.\n\nClass: Magician\nCategory: Hero\n\nPrimary Weapon: Shining Rod\nSecondary Weapon: Light Orb\nPrimary Stat: INT\nSecondary Stat: LUK\n\nAdvancement Route:\nI:Luminous -> II:Luminous -> III:Luminous -> IV:Luminous\n',
            },
        'Mercedes': {
            'class': 'Bowman',
            'category': 2,
            'Weapon': ['Dual Bowgun'],
            'Secondary': ['Magic Arrow'],
            'Emblem': ['Boss Arena'],
            '# str': 34, '% str': 0,
            '# dex': 1269, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 90, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 120, '% accuracy': 0.1,
            '# avoid': 0, '% avoid': 0.6,
            '# hp': 1500, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 40, '# max speed': 165, '# jump': 20,
            '% mastery': 0.85,
            '% Boss Damage': 0.15,
            '% Ignore Defense': 0.25,
            '% Ignore Resistance': 0.25,
            '% Total Damage': 0.45,
            '% Final Damage': 0,
            '% Crit Rate': 0.7,
            '% Min Crit': 0.35,
            '% Max Crit': 0.8,
            '% Status Resistance': 0.25,
            '% Skill Damage': 2,
            '% Hyper Reinforce': 0.7,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0.55,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Ishtar\'s Ring - Reinforce', 'Ishtar\'s Ring - Boss Rush', 'Ishtar\'s Ring - Guardbreak', 'Unicorn Spike', 'Lightning Edge', 'Spikes Royale', 'Spikes Royale - Armorbreak'],
            'description':'Mercedes is the one of the six Heroes who sealed away the Black Mage and is part of the Archer branch. She uses Dual Bowguns and Magic Arrows for weapons.\nMercedes is the Queen of the Elves, who have been asleep for hundreds of years. Mercedes and her people were cursed by the Black Mage before he was sealed, causing the elves to fall into a long sleep. Before succumbing to the curse, Mercedes sealed the elves\' home of Elluel so that no one could enter while the curse still held sway.\n\nClass: Bowman\nCategory: Hero\n\nPrimary Weapon: Dual Bowgun\nSecondary Weapon: Magic Arrow\nPrimary Stat: DEX\nSecondary Stat: STR\n\nAdvancement Route:\nI:Mercedes -> II:Mercedes -> III:Mercedes -> IV:Mercedes\n',
            },
        'Phantom': {
            'class': 'Thief',
            'category': 2,
            'Weapon': ['Cane'],
            'Secondary': ['Card'],
            'Emblem': ['Boss Arena'],
            '# str': 4, '% str': 0,
            '# dex': 44, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 1339, '% luk': 0,
            '# watt': 110, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 200, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0.2,
            '# hp': 0, '% hp': 0.3,
            '# mp': 0, '% mp': 0.3,
            '# all stats': 0, '% all stats': 0,
            '# speed': 35, '# max speed': 160, '# jump': 20,
            '% mastery': 0.9,
            '% Boss Damage': 0,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.3,
            '% Final Damage': 0.8,
            '% Crit Rate': 0.7,
            '% Min Crit': 0.35,
            '% Max Crit': 0.5,
            '% Status Resistance': 0.45,
            '% Skill Damage': 3,
            '% Hyper Reinforce': 0,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0.2,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Penombre'],
            'description':'Phantom is one of the six Heroes who sealed away the Black Mage and is part of the Thief branch. Using a Cane and Cards, Phantom has the unique ability to copy skills from Explorers as well as from monsters.\nA century ago, Phantom was famous among the wealthy merchants and noblemen. He deliberately left traces when stealing, and even then people did not even know who he was. However, the death of Aria, the Empress before Cygnus, with whom he had fallen in love with while trying to steal the great treasure of Ereve, caused him to join the Heroes to take revenge on the Black Mage.\n\nClass: Thief\nCategory: Hero\n\nPrimary Weapon: Cane\nSecondary Weapon: Card\nPrimary Stat: LUK\nSecondary Stat: DEX, STR\n\nAdvancement Route:\nI:Phantom -> II:Phantom -> III:Phantom -> IV:Phantom\n',
            },
        'Shade': {
            'class': 'Pirate',
            'category': 2,
            'Weapon': ['Knuckle'],
            'Secondary': ['Fox Marble'],
            'Emblem': ['Boss Arena'],
            '# str': 1299, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 20, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 2000, '% wdef': 0,
            '# mdef': 2000, '% mdef': 0,
            '# accuracy': 420, '% accuracy': 0,
            '# avoid': 300, '% avoid': 0,
            '# hp': 0, '% hp': 0.2,
            '# mp': 0, '% mp': 0.2,
            '# all stats': 0, '% all stats': 0,
            '# speed': 20, '# max speed': 140, '# jump': 0,
            '% mastery': 0.9,
            '% Boss Damage': 0.3,
            '% Ignore Defense': 0.3,
            '% Ignore Resistance': 0,
            '% Total Damage': 0.2,
            '% Final Damage': 0,
            '% Crit Rate': 0.15,
            '% Min Crit': 0.4,
            '% Max Crit': 0.7,
            '% Status Resistance': 0.4,
            '% Skill Damage': 3.8,
            '% Hyper Reinforce': 0.4,
            '% Hyper Boss Rush': 0.2,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'Hyper related': ['Spirit Claw - Reinforce', 'Spirit Claw - Boss Rush', 'Weaken'],
            'description':'Shade is one of the six Heroes who sealed away the Black Mage, and is part of the Pirate branch. Shade uses Knuckle as primary weapon and Fox Marble as secondary weapon, and calls on the power of spirits for aid.\nDuring the final battle with the Black Mage, Shade stepped forward to perform the ultimate sacrifice to seal away the Black Mage. Evidence of his existence being wiped out, he was cursed and banished to the world of Vulpes, where he woke up centuries later.\n\nClass: Pirate\nCategory: Hero\n\nPrimary Weapon: Knuckle\nSecondary Weapon: Fox Marble\nPrimary Stat: STR\nSecondary Stat: DEX\n\nAdvancement Route:\nI:Shade -> II:Shade -> III:Shade -> IV:Shade\n',
            },
        ##
        'dummy': {
            'class': 'dummy',
            'category': 2,
            'Weapon': ['Wand'],
            'Secondary': ['Jewel'],
            'Emblem': ['Boss Arena'],
            '# str': 1239, '% str': 0,
            '# dex': 4, '% dex': 0,
            '# int': 4, '% int': 0,
            '# luk': 4, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.15,
            '% Min Crit': 0.2,
            '% Max Crit': 0.5,
            '% Status Resistance': 0,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0,
            '% Hyper Boss Rush': 0,
            '% Hyper Guard Break': 0,
            '% Hyper Critical': 0,
            '# Skill Delay': [1],
            'description':'\n\nClass: Magician\nCategory: Hero\n\nPrimary Weapon: dummy\nSecondary Weapon: dummy\nPrimary Stat: INT\nSecondary Stat:LUK\n\nAdvancement Route:\nI:Xenon -> II:Xenon -> III:Xenon -> IV:Xenon\n',
            },
        
        'Xenon': {
            'class': 'Thief, Pirate',
            'Weapon': ['Whip Blade'],
            'Secondary': ['dummy'],
            'Emblem': ['dummy'],
            '# str': 1239, '% str': 0,
            '# dex': 1239, '% dex': 0,
            '# int': 1239, '% int': 0,
            '# luk': 1239, '% luk': 0,
            '# watt': 0, '% watt': 0,
            '# matt': 0, '% matt': 0,
            '# wdef': 0, '% wdef': 0,
            '# mdef': 0, '% mdef': 0,
            '# accuracy': 0, '% accuracy': 0,
            '# avoid': 0, '% avoid': 0,
            '# hp': 0, '% hp': 0,
            '# mp': 0, '% mp': 0,
            '# all stats': 0, '% all stats': 0,
            '# speed': 0, '# max speed': 140, '# jump': 0,
            '% mastery': 0,
            '% Boss Damage': 0,
            '% Ignore Defense': 0,
            '% Ignore Resistance': 0,
            '% Total Damage': 0,
            '% Final Damage': 0,
            '% Crit Rate': 0.05,
            '% Min Crit': 0.2,
            '% Max Crit': 0.5,
            '% Status Resistance': 0,
            '% Skill Damage': 0,
            '% Hyper Reinforce': 0,
            '# Skill Delay': [1],
            'description':'Xenon is a member of the Resistance. He is a mixture of Thief and Pirate, therefore using Strength, Dexterity, and Luck as his main stats. With a Whip Blade and a Controller, Xenon uses technology and quick-paced attacks to eliminate his enemies. Originally a weapon created by Gelimer, Xenon escaped and joined the Resistance.\n\nClass: Thief, Pirate\nCategory: Resistance\n\nPrimary Weapon: Whip Blade\nSecondary Weapon: Core Controller\nPrimary Stat: STR, DEX, LUK\n\nAdvancement Route:\nI:Xenon -> II:Xenon -> III:Xenon -> IV:Xenon\n',
            },
        }
    m_weaponMultiplier = {
        'None': 0,
        'One-handed Sword': 1.2,
        'Two-handed Sword': 1.34,
        'One-handed Axe': 1.2,
        'Two-handed Axe': 1.34,
        'One-handed Mace': 1.2,
        'Two-handed Mace': 1.34,
        'Spear': 1.49,
        'Polearm': 1.49,
        'Wand': [1.2, 1],
        'Staff': [1.2, 1],
        'Bow': 1.3,
        'Crossbow': 1.35,
        'Claw': 1.75,
        'Dagger': 1.3,
        'Gun': 1.5,
        'Knuckle': 1.7,
        'Katara': 1.3,
        'Cane': 1.3,
        'Whip Blade': 1.5,
        'Desperado': 1.3,
        'Shining Rod': 1.2,
        'Cannon': 1.8,
        'Soul Shooter': 1.7,
        'Katana': 1.25,
        'Fan': 1.35,
        'Long Sword': 1.34,
        'Great Sword': 1.49,
        'Dual Bowguns': 1.32,
        }

if __name__ == '__main__':
    print JobLib.m_job['Bow Master'].keys()
        
            
